version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: catfeed_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
    name: catfeed_redis_data 