"""Initial migration

Revision ID: 762b46a66e59
Revises: 
Create Date: 2025-01-13 19:16:40.695559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '762b46a66e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.create_unique_constraint('uq_admin_username', ['username'])
        batch_op.drop_column('password_history')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('last_password_change')
        batch_op.drop_column('force_password_change')

    with op.batch_alter_table('cat_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('target_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('daily_calories', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meals_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_neutered')
        batch_op.drop_column('activity_level')

    with op.batch_alter_table('feeding_record', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('calories',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_feeding_record_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('unit')
        batch_op.drop_column('feeder_nickname')
        batch_op.drop_column('food_type')

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('upload_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('date_taken')
        batch_op.drop_column('description')
        batch_op.drop_column('photographer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photographer', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('date_taken', sa.DATETIME(), nullable=False))
        batch_op.alter_column('upload_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size')

    with op.batch_alter_table('feeding_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('feeder_nickname', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_index(batch_op.f('ix_feeding_record_timestamp'))
        batch_op.alter_column('calories',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('cat_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_level', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_neutered', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('meals_per_day')
        batch_op.drop_column('daily_calories')
        batch_op.drop_column('target_weight')
        batch_op.drop_column('birthday')
        batch_op.drop_column('name')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_password_change', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('last_password_change', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('password_history', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_admin_username', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('last_login')
    # ### end Alembic commands ###
